### ISSUE TITLE
included "Go Back" functionality on a page results in automatic return to previous page instead to the next page

### ISSUE THREAD

**Issue by TobiStahl** [comproso/framework#1]

**Comment by thku** [comment]
1. Is the latest version of the framework as well as of the other packages installed?
2. Is still a typo (should be repetitions instead of repititions) on one of the following places:
   - CSV-seeder files on the first row
   - Database pages table
3. Is the value of the following input field 0 ?
   `<input type="hidden" name="cctrl_prvs" value="0">`

**Comment by thku** [comment]
This was a browser cache issue…
